version: "3.9"
services:
  azure-vote-back:
    image: redis:latest
    container_name: azure-vote-back
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 6379:6379

  azure-vote-front:
    image: azure-vote-front
    container_name: azure-vote-front
    depends_on:
      - azure-vote-back
    build:
      context: azure-vote
      dockerfile: ./Dockerfile
    environment:
      ConnectionStrings__RedisHost: azure-vote-back
      # Set the following parameter to true if you want to send traces and metrics to the local OTEL collector
      EnableOTLPExporter: false
      ConnectionStrings__OTLPMetricsExporterEndpoint: http://azure-vote-collector:4318/v1/metrics
      ConnectionStrings__OTLPTracesExporterEndpoint: http://azure-vote-collector:4318/v1/traces
    ports:
      - 80:80

  azure-vote-collector:
    image: otel/opentelemetry-collector:latest
    container_name: azure-vote-collector
    ports:
      - 4318:4318
    profiles:
      - local-collector
